language: rust
cache: cargo

before_install:
  - rustup component add clippy
install: true

jobs:
  include:
    - name: 'fmt'
      rust: stable
      before_install:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check

    - name: 'test (stable)'
      rust: stable
      script: &test-script
        - cargo clippy --locked --all-targets -- --deny clippy::all --deny warnings
        - cargo test

    - name: 'test (nightly)'
      rust: nightly
      script: *test-script

    - name: 'docs (nightly)'
      rust: nightly
      script:
        - RUSTDOCFLAGS="-D intra-doc-link-resolution-failure" cargo doc --all-targets --no-deps --document-private-items

  fast_finish: true
