os: linux
dist: focal

.rust: &rust
  language: rust
  cache: cargo

jobs:
  fast_finish: true
  include:
    - name: "fmt"
      <<: *rust
      cache: false
      rust: stable
      before_install:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check

    - &test
      name: "test (stable)"
      <<: *rust
      rust: stable
      services: [docker]
      before_install:
        - rustup component add clippy
      script: ./ci/run.sh

    - <<: *test
      name: "test (nightly)"
      rust: nightly

    - name: "docs (nightly)"
      <<: *rust
      rust: nightly
      script: ./scripts/build-docs.sh

    - name: "muxrpc-test-suite"
      language: node
      node_js: 12
      cache: yarn
      before_install:
        - cd muxrpc/muxrpc-test-suite
      install:
        - yarn --frozen-lockfile install
      script:
        - yarn run lint
        - yarn run test
