language: rust
rust:
- stable
- nightly
cache: cargo
install:
- rustup component add clippy rustfmt
script:
- cargo fmt --all -- --check
- cargo clippy --locked --all-targets -- --deny clippy::all
- cargo test
