language: rust
cache: cargo

before_install:
  - rustup component add clippy

jobs:
  include:
    - name: 'fmt'
      rust: stable
      before_install:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check

    - &test
      name: 'test (stable)'
      rust: stable
      services: [docker]
      script: &test-script
        - cargo clippy --locked --all-targets -- --deny clippy::all --deny warnings
        - DETACH=true ./tests/ssb-server.sh
        - cargo test

    - <<: *test
      name: 'test (nightly)'
      rust: nightly

    - name: 'docs (nightly)'
      rust: nightly
      script:
        - RUSTDOCFLAGS="-D intra-doc-link-resolution-failure" cargo doc --no-deps --document-private-items

  fast_finish: true
